name: Test pysteps-nwp-importers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    name: Unit Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [ "3.7", "3.9" ]
      max-parallel: 6

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install mamba and create environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/ci_test_env.yml
          environment-name: test_environment
          extra-specs: python=${{ matrix.python-version }}

      - name: Install pysteps
        if: matrix.os != 'macos-latest'
        working-directory: ${{github.workspace}}
        run: pip install .

      - name: Download test data
        env:
          PYSTEPS_DATA_PATH: ${{github.workspace}}/pysteps_data
        working-directory: ${{github.workspace}}/ci
        run: python download_test_data.py

      - name: Check imports
        working-directory: ${{github.workspace}}/pysteps_data
        run: |
          python --version
          python -c "import pysteps_nwp_importers"

      - name: Run tests
        working-directory: ${{github.workspace}}/pysteps_data
        run: pytest --pyargs pysteps_nwp_importers